[source]
center = [0.125, 0.125, 0.0]
radius = 0.02
amplitude = 0.1
frequency = 100

[material]
inclusion_density = 8.0
inclusion_wave_speed = 3.0
outer_density = 1.0
outer_wave_speed = 1.5

[mesh]
cell_size = 0.007
box_size = 0.25
inclusion_radius = 0.05

[solver]
total_time = 1.0
polynomial_order = 4

[receivers]
pressure = [[0.125, 0.125, 0.0]]
x_velocity = [[0.125, 0.125, 0.0],
	      [0.125, 0.125, 0.1]]
y_velocity = [[0.125, 0.125, 0.0]]
z_velocity = [[0.125, 0.125, 0.0]]

[output_intervals]
image = 10
data = 100
points = 10
energy = 50
